export const pages = [
  "https://www.maxfashion.com/ae/en/c/mxmen",
  "https://www.maxfashion.com/ae/en/c/mxwomen",
  "https://www.maxfashion.com/ae/en/c/mxkids-girlstwotoeightyrs",
  "https://www.maxfashion.com/ae/en/c/mxkids-boystwotoeightyrs",
  "https://www.maxfashion.com/ae/en/c/mxkids-girlseighttosixteenyrs",
  "https://www.maxfashion.com/ae/en/c/mxkids-boyseighttosixteenyrs",
  "https://www.maxfashion.com/ae/en/c/mxkids-shoes-girlstwotoeightyrs",
  "https://www.maxfashion.com/ae/en/c/mxkids-shoes-girlseighttosixteenyrs",
  "https://www.maxfashion.com/ae/en/c/mxkids-shoes-boyseighttosixteenyrs",
  "https://www.maxfashion.com/ae/en/c/mxkids-shoes-boystwotoeightyrs",
];

export const colors = [
  "beige",
  "black",
  "blue",
  "brown",
  "cream",
  "gold",
  "green",
  "grey",
  "multicolour",
  "orange",
  "pink",
  "purple",
  "red",
  "white",
  "yellow",
];
