export const bottom = [
  "pant", // singular form of pants
  "pants", // plural form of pant
  "jean", // singular form of jeans
  "jeans", // plural form of jean
  "trouser", // singular form of trousers
  "trousers", // plural form of trouser
  "legging", // singular form of leggings
  "leggings", // plural form of legging
  "skirt", // singular and plural form are the same
  "short", // singular form of shorts
  "shorts", // plural form of short
  "bermuda", // singular and plural form are the same
  "jogger", // singular form of joggers
  "joggers", // plural form of jogger
  "cargo", // singular and plural form are the same
  "khaki", // singular and plural form are the same
  "chino", // singular and plural form are the same
  "chinos",
  "denim", // singular and plural form are the same
  "sweatpant", // singular form of sweatpants
  "sweatpants", // plural form of sweatpant
  "jegging", // singular form of jeggings
  "jeggings", // plural form of jegging
  "wideleg",
  "trackpants",
  "slack",
  "slacks",
  "shalwar",
  "tights",
  "baggy",
  "lycra",
];

export const footwear = [
  "ballerina",
  "flipflop",
  "flipflops",
  "slide",
  "slides",
  "espadrille",
  "espadrilles",
  "wedge",
  "wedges",
  "loafer",
  "loafers",
  "oxford",
  "oxfords",
  "derbie",
  "derbies",
  "monk strap",
  "monk straps",
  "brogue",
  "brogues",
  "boot",
  "boots",
  "flat",
  "flats",
  "heel",
  "heels",
  "heeled",
  "sandal",
  "sandals",
  "sneaker",
  "sneakers",
  "slipper",
  "slippers",
  "shoe",
  "shoes",
  "bootie",
];

export const bag = [
  "backpack",
  "backpacks",
  "tote",
  "totes",
  "messenger",
  "messengers",
  "duffel",
  "duffels",
  "shoulder",
  "crossbody",
  "crossbodies",
  "hobo",
  "hobos",
  "satchel",
  "satchels",
  "weekender",
  "weekenders",
  "suitcase",
  "suitcases",
  "laptop",
  "travel",
  "gym",
  "bucket",
  "drawstring",
  "waist",
  "briefcase",
  "briefcases",
  "sling",
];

export const hat = [
  "beanie",
  "beanies",
  "baseballcap",
  "baseballcaps",
  "buckethat",
  "buckethats",
  "fedora",
  "fedoras",
  "khaki",
  "trilby",
  "trilbies",
  "boater",
  "boaters",
  "bowlerhat",
  "bowlerhats",
  "beret",
  "berets",
  "snapback",
  "newsboy",
  "visor",
  "visors",
  "sunhat",
  "sunhats",
  "cowboyhat",
  "cowboyhats",
  "flatcap",
  "flatcaps",
  "panamahat",
  "panamahats",
  "sombrero",
  "sombreros",
  "fez",
  "fezzes",
  "deerstalker",
  "deerstalkers",
  "cloche",
  "cloches",
  "fascinator",
  "fascinators",
  "kufi",
  "kufis",
  "trapperhat",
  "trapperhats",
  "golfhat",
  "golfhats",
  "knithat",
  "knithats",
  "rainhat",
  "rainhats",
  "strawhat",
  "strawhats",
  "fishermanhat",
  "fishermanhats",
  "booniehat",
  "booniehats",
  "pillboxhat",
  "pillboxhats",
  "chullo",
  "chullos",
  "hat",
  "hats",
  "cap",
  "caps",
];

export const outerwear = [
  "kimono",
  "peacoat",
  "peacoats",
  "trenchcoat",
  "trenchcoats",
  "cardigan",
  "cardigans",
  "sweater",
  "sweaters",
  "cape",
  "capes",
  "poncho",
  "ponchos",
  "shawl",
  "shawls",
  "overcoat",
  "overcoats",
  "gilet",
  "gilets",
  "anorak",
  "anoraks",
  "duster",
  "dusters",
  "snowsuit",
  "snowsuits",
  "peacoat",
  "peacoats",
  "pullover",
  "pullovers",
  "blouson",
  "blousons",
  "cagoule",
  "cagoules",
  "jerkin",
  "jerkins",
  "cloak",
  "cloaks",
  "windcheater",
  "windcheaters",
  "jacket",
  "jackets",
  "coat",
  "coats",
  "blazer",
  "blazers",
  "parka",
  "parkas",
  "windbreaker",
  "windbreakers",
  "raincoat",
  "raincoats",
  "vest",
  "vests",
  "poncho",
  "ponchos",
  "robe",
  "puffer",
  "winterjacket",
];

export const underwear = [
  "boxer",
  "boxers",
  "underpant",
  "underpants",
  "brief",
  "briefs",
  "trunk",
  "trunks",
  "jockstrap",
  "camisole",
  "jockstraps",
  "thong",
  "thongs",
  "hipster",
  "hipsters",
  "boyshort",
  "boyshorts",
  "g-string",
  "gstring",
  "g-strings",
  "gstrings",
  "shapewear",
  "shapewears",
  "cami",
  "camis",
  "chemise",
  "chemises",
  "corset",
  "corsets",
  "bustier",
  "bustiers",
  "teddy",
  "teddies",
  "bustle",
  "bustles",
  "tanga",
  "tangas",
  "panty",
  "panties",
  "bikini",
  "bikinis",
  "nightgown",
  "nightgowns",
  "sock",
  "socks",
  "panty",
  "pantyhose",
  "rope",
  "lycra",
  "strap",
  "undershirt",
];

export const formal = [
  "suit",
  "suits",
  "tuxedo",
  "tuxedos",
  "dress",
  "dresses",
  "gown",
  "gowns",
  "wedding",
  "evening",
  "prom",
  "abaya",
  "kurta",
  "jalabiya",
  "kaftan",
];

export const top = [
  "t-shirt",
  "tshirt",
  "blouse",
  "shirt",
  "tank",
  "polo",
  "sweater",
  "hoodie",
  "tunic",
  "croptop",
  "peplum",
  "halter",
  "wraptop",
  "off-theshoulder",
  "offtheshoulder",
  "bellsleeve",
  "bell-sleeve",
  "buttondown",
  "button-down",
  "hollow",
  "flannel",
  "tube",
  "cold-shoulder",
  "coldshoulder",
  "cowl",
  "raglan",
  "mock",
  "tiefront",
  "tie-front",
  "lace",
  "mesh",
  "sequin",
  "sweatshirt",
  "vest",
  "corset",
  "bodysuit",
  "peasant",
  "muscle",
  "ruffle",
  "ruffled",
  "spaghettistrap",
  "shrug",
  "longsleeve",
  "longsleeves",
  "shortsleeve",
  "shortsleeves",
  "batwing",
  "pullover",
  "crewneck",
  "v-neck",
  "vneck",
  "boatneck",
  "top",
  "turtleneck",
  "jersey",
  "strap",
];

export const set = [
  "pajama",
  "pajamas",
  "twopiece",
  "tracksuit",
  "jumpsuit",
  "playsuit",
  "bottomtop",
  "overall",
  "sweatsuit",
  "bodysuit",
  "capri",
  "bodysuit",
  "bodysuits",
  "dungaree",
  "romper",
  "prayerdress",
  "set",
  "combination",
];
