export const clothing = [
  { url: "https://www.sivvi.com/uae-en/men/mens-clothing", gender: "men" },
  { url: "https://www.sivvi.com/uae-en/women/womens-clothing", gender: "women" },
  { url: "https://www.sivvi.com/uae-en/kids/boys/boys-clothing", gender: "boys" },
  { url: "https://www.sivvi.com/uae-en/kids/girls/girls-clothing", gender: "girls" },
];

export const others = [
  { url: "https://www.sivvi.com/uae-en/kids/boys/boys-shoes", gender: "boys", category: "footwear" },
  { url: "https://www.sivvi.com/uae-en/kids/girls/girls-shoes", gender: "girls", category: "footwear" },
  { url: "https://www.sivvi.com/uae-en/men/mens-shoes", gender: "men", category: "footwear" },
  { url: "https://www.sivvi.com/uae-en/women/womens-bags", gender: "women", category: "bag" },
];

export const colors = [
  "beige",
  "black",
  "blue",
  "brown",
  "green",
  "grey",
  "multicolour",
  "orange",
  "pink",
  "purple",
  "red",
  "silver",
  "gold",
  "white",
  "yellow",
];

export const materials = [
  "Velvet",
  "acrylic",
  "acrylic_blend",
  "bamboo",
  "canvas",
  "cashmere",
  "cashmere_blend",
  "chiffon",
  "combination",
  "cotton",
  "cotton_blend",
  "cotton_polyester",
  "crepe",
  "dacron",
  "denim",
  "elastane",
  "elastane_blend",
  "fabric",
  "flannel",
  "georgette",
  "jacquard",
  "jersey",
  "jute",
  "lace",
  "leather",
  "linen",
  "linen_blend",
  "lycra",
  "lyocell",
  "mesh",
  "metal",
  "microfibre",
  "modal",
  "modal_blend",
  "net",
  "nylon",
  "nylon_blend",
  "poly_crepe",
  "polyamide",
  "polyamide_blend",
  "polyester",
  "polyester_blend",
  "polyester_pu",
  "polyester_spandex",
  "polysatin",
  "polyster_blend",
  "polyurethane",
  "pu",
  "pvc",
  "ramie",
  "rayon",
  "rayon_blend",
  "satin",
  "sequin",
  "silk",
  "silk_blend",
  "silk_satin",
  "spandex",
  "suede_leather",
  "synthetic",
  "tencel",
  "textile",
  "tulle",
  "velvet",
  "viscose",
  "viscose_blend",
  "wool",
  "wool_blend",
];
